language: node_js
node_js:
- '6'
before_install:
- npm install -g gulp
install:
- npm install --ignore-scripts && typings install
script:
- gulp build
deploy:
- provider: npm
  email: jesper@superfly.tv
  api_key:
    secure: NEBXS9TANvOz4VVFJ1g0GJMbXbV0UIhGvWn2HUCTAFZhLezeMAooe70Cq5SGW9YfG7pIhrVQjV+WS4JST7Ej3dkNEsy5pPBsCao4wAvigUZ2jutzlC3Ayb+7dbi0O12hwJLKPpEKkJBzFHAirpKLtDwbV+OR+WtEP0JSXiMIQ576m5KrNmFkF7P2uLa4ZdTf1MUZyk6ieQmRoMMyaKv536ytSDUzqAIpzcgRTmBEUJ3kpj0q9LMQ+IETZ1IylMuvlOUKdgLg/eOaDnCDGQhnR9V7jaErmOm8Ognw4aUtVz6G+WwvIxKR3p2WqnA9oOw8MTf4qQHkbIYEmQuq1o4Y9iVyPvZ6mErHl0jQrBxGT7PcWxhcqyb/9tfjFCua9H+SYJbhX3sPX4yeFPYAw3QJZAPX4kuK114dM6Ar9Dp0mxzrrAFeVjwZRFsVvvWMT6ILHEZUiodGxq5sIw0b1EIGhd+gJ5Mo0dMmiNWZHQ1VjN5IEoghKYvv/GYfnZXHndIcKKhph4mlKzXlvp2ILr65LNQ7086BEhbEbwvg4DiQT4cdmP0GAFYeb5zZR2ACY5ayf/p9im5OMCf7Jy9kpSe+lvXo6oH/eNYaAzoqUNturNZ4/zyntUa03MfLIj0CkuLnJ9L3f4LfpNzOVFofX49qdh8EcckXjhmt//MU4RiP2CY=
  skip_cleanup: true
  on:
    tags: true
    repo: SuperFlyTV/casparcg-connection
    branch: master
- provider: releases
  api_key:
    secure: L+tS772fbysRMXZpAPLusyAlqXDJKDsybmMYR0iQ0jqkEHFlRZ44K9v0FMHTXULaRIGqTka9PtSkjghjSQpxV3bQr+L9rgez6uJIdU+Iow/yY6mGXDPutYFkP8Csezg4FyXmFYdakDY8WGlVECbCvjWgR/YDvZzATtlyUCXmiIYxpGAVWxsHyfBm2aMoCfIjbTioDJ0XPs/kFVgRD1HfJFMuDdVePv408aSxownHEXi7VRsykTEzCp3T1Kz8iw6h4/JMzdbvLpUiieLsKLmsv+eNMGoDTjmufn44rkRsJR6lbxOUtDrA1kJZGUu7kaZmcf4pBHBvEvLFzoEo4857XLcFSGi8aEYk+PXmI3Z6/ir8px8qVdhrpfDWirlZj1NUouALXQeKIeMAbaJqmzJgbZ+Gnye1HL1Tn6ddJ+oxhKlC3h2oGPCDRfhjmxPMlwGOX0af1mvGS/8FEqGZt1Me3jG+/6okn9jSxX8wvddSq9+MLpVZ2PaP0pdTA3B2paBm/E76XWfRfSaw5Ai64PZSHAtd+h4B6FiEx7xxVp6dxAoINimJO6m8TXiTJY/iJWFCOConHgOrfIH2BsIkFsXHBEspJn05aH44FmzZy+cKx03OEI0+z9Zm4glEW+UVyUslG0l1edSnzIqgr8LLp/F+kUFOTsoxYBqtLfnbThrR9Xw=
  file: 
  - "js/"
  - "LICENSE"
  - "package.json"
  - "README.md"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: SuperFlyTV/casparcg-connection
    branch: master
notifications:
  email:
    recipients:
    - jesper@superfly.tv
    on_success: change
    on_failure: change
  slack:
    secure: AosyVI/J6Drv9TeM6yMm9rOKJR90B6abPuQjM/TZ4s4ZvoG8xyMe7vmm1CFqmQLvaUsC33N7fye9dSJgO9M4z3YrVCmq6yYC6eCxDMWqMsJQWsM8bcuxb8EAdMLKZsANOLAxug5l6EPteaZyJUjaaEm4hMyx232ZSzOxmBS1VSmblgcR0VM7dGvwxEXqc+ADASEZqEKqF1SS0NPRIgQ4PXFsyJ0DjYdMQvTSEHBefs1tBPi7+wwmvdo+NwklCQ1k0tPDDwjQvXA0AO4ERSczBWAByBLy8yDZ9zHCSuInTYmwJbQ6cRE5YqXxRRd2GChm3hYlIjK/OPEmJTJssf4YnZJh76ukpFajIBMdk7msUvzdwuLHU+Bc4fQMn9TUGRcUsJtbSJVlD4E5pmvRnr1jA+1WchyBAtGPMNuktZwZAPQY14DSk+2NLYXtk3pSt2swcWhjvFl+VmXMcde6cy3mUBtEFiyMEzGU0gJUi6+KkMDWBYruK8Mj1z/aT4tAAaHFzWxilHtkE8/b7K/XSKdWDVun/0zlzK+AZVDg2Hyplgxu1J4atbSag7kOeDR6tGqMMFe+iJCNCDi2FXnaZmCY0CJqImCcfIN1pd5uUdn7eefQQhCuwkbM+6HIqn8MB2Y5K5B6fECmHqOMIOokWDaVRVAPhIXblWy+ubri0ojBP2A=